// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmlGd4WUmYAn09HkKIsWKsrx1H2Hg44k',
    appId: '1:767551108049:web:d4c5dbbc9cdfbcba4ce6f0',
    messagingSenderId: '767551108049',
    projectId: 'ptsd-free1',
    authDomain: 'ptsd-free1.firebaseapp.com',
    storageBucket: 'ptsd-free1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALtul8zes_M5Etwy5j8OhWcOSDeZk1YXo',
    appId: '1:767551108049:android:bc65aedbd64e86a54ce6f0',
    messagingSenderId: '767551108049',
    projectId: 'ptsd-free1',
    storageBucket: 'ptsd-free1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIIT5jU2Bbr48MiS6GyMcz0AHDmhf278',
    appId: '1:767551108049:ios:bd209fba499908b74ce6f0',
    messagingSenderId: '767551108049',
    projectId: 'ptsd-free1',
    storageBucket: 'ptsd-free1.appspot.com',
    iosBundleId: 'com.example.ptsdFree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIIT5jU2Bbr48MiS6GyMcz0AHDmhf278',
    appId: '1:767551108049:ios:1d1debd774d103224ce6f0',
    messagingSenderId: '767551108049',
    projectId: 'ptsd-free1',
    storageBucket: 'ptsd-free1.appspot.com',
    iosBundleId: 'com.example.ptsdFree.RunnerTests',
  );
}
